---
version: 1.0
lm_model:
  node_lm_models:
    -
      lm_type: bert
      model_name: "bert-base-uncased"
      gradient_checkpoint: true
      node_types:
        - node
gsf:
  basic:
    model_encoder_type: rgcn
    graph_name: ogbn-arxiv
    backend: gloo
    ip_config: ip_list.txt
    part_config: /data/ogbn-arxiv-1p/ogbn-arxiv.json
    verbose: false
  lm: 
    lm_train_nodes: 10
    lm_infer_batch_size: 32
    freeze_lm_encoder_epochs: 0
  gnn:
    fanout: "15,10"
    num_layers: 2
    hidden_size: 128
    use_mini_batch_infer: true
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.5
    lr: 0.001
    lm_tune_lr: 0.0001
    num_epochs: 10
    batch_size: 1024
    bert_infer_bs: 1024
    wd_l2norm: 0
    no_validation: false
  rgcn:
    num_bases: -1
    use_self_loop: true
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  node_classification:
    target_ntype: "node"
    label_field: "labels"
    multilabel: false
    num_classes: 40
