---
version: 1.0
lm_model:
  node_lm_models:
    -
      lm_type: bert
      model_name: "bert-base-uncased"
      gradient_checkpoint: true
      node_types:
        - paper
        - subject
gsf:
  basic:
    model_encoder_type: rgcn
    backend: gloo
    verbose: false
  lmgnn:
    lm_train_nodes: 10
    fanout: "50,50"
    num_layers: 2
    hidden_size: 256
    use_mini_batch_infer: false
    training_method:
      name: glem
      kwargs:
        em_order_gnn_first: false
        inference_using_gnn: true
        pl_weight: 0.5
        num_pretrain_epochs: 0
        lm_param_group:
          - pure_lm
          - node_proj_matrix
          - node_input_projs
          # - sparse_embed
        gnn_param_group:
          - node_input_projs
          - node_proj_matrix
          - sparse_embed
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embeds_path: null
  hyperparam:
    dropout: 0.
    lr: 0.0001
    lm_tune_lr: 0.0001
    num_epochs: 20
    batch_size: 1024
    wd_l2norm: 0
    alpha_l2norm: 0.
    no_validation: true
  rgcn:
    num_bases: -1
    use_self_loop: true
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  node_classification:
    target_ntype: "paper"
    label_field: "label"
    multilabel: false
    num_classes: 14
